### PR TITLE
Mycujoo icons

### PR DESCRIPTION
**Pull request by vitaliykibish**

### CODE REVIEW

**Comment by aaronatmycujoo** [comment]
Awesome!! 🎉 

Can you rename the icon to `IconLineup` so removing the `Dark` suffix? :3

**Comment by aaronatmycujoo** [comment]
It's parsed in the `build.js` file. He renamed it to align with the way that material-icons named their icons so we can use the same script to parse both.

https://github.com/mycujoo/material-icons/blob/master/build.js#L58-L59

Is the part that does it

**Comment by rgalus** [comment]
True, my bad

**Comment by rictorres** [comment]
btw, it seems your github account is not connected with your local git configs.

image

image

☺️

**Pull request merged**
